api = "0.10"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/node-engine"
  id = "paketo-buildpacks/node-engine"
  name = "Paketo Buildpack for Node Engine"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/node-engine/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/amd64/bin/optimize-memory", "linux/amd64/bin/inspector", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run", "linux/arm64/bin/optimize-memory", "linux/arm64/bin/inspector", "buildpack.toml"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"
  [metadata.default-versions]
    node = "22.*.*"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:deaf9695966087815a09c1c8e7fb0cfeb5b5b4471836e5993431230a845becad"
    cpe = "cpe:2.3:a:nodejs:node.js:18.20.7:*:*:*:*:*:*:*"
    deprecation_date = "2025-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "Zlib", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v18.20.7?checksum=deaf9695966087815a09c1c8e7fb0cfeb5b5b4471836e5993431230a845becad&download_url=https://nodejs.org/dist/v18.20.7/node-v18.20.7-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v18.20.7/node-v18.20.7-linux-x64.tar.xz"
    source-checksum = "sha256:deaf9695966087815a09c1c8e7fb0cfeb5b5b4471836e5993431230a845becad"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v18.20.7/node-v18.20.7-linux-x64.tar.xz"
    version = "18.20.7"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:c788ad58ded0426a7fca9f3a7e005f57c14a348ebdb3a2977e19ef7b0c143439"
    cpe = "cpe:2.3:a:nodejs:node.js:18.20.7:*:*:*:*:*:*:*"
    deprecation_date = "2025-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "Zlib", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v18.20.7?checksum=c788ad58ded0426a7fca9f3a7e005f57c14a348ebdb3a2977e19ef7b0c143439&download_url=https://nodejs.org/dist/v18.20.7/node-v18.20.7-linux-arm64.tar.xz"
    source = "https://nodejs.org/dist/v18.20.7/node-v18.20.7-linux-arm64.tar.xz"
    source-checksum = "sha256:c788ad58ded0426a7fca9f3a7e005f57c14a348ebdb3a2977e19ef7b0c143439"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v18.20.7/node-v18.20.7-linux-arm64.tar.xz"
    version = "18.20.7"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:5467ee62d6af1411d46b6a10e3fb5cacc92734dbcef465fea14e7b90993001c9"
    cpe = "cpe:2.3:a:nodejs:node.js:18.20.8:*:*:*:*:*:*:*"
    deprecation_date = "2025-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "Zlib", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v18.20.8?checksum=5467ee62d6af1411d46b6a10e3fb5cacc92734dbcef465fea14e7b90993001c9&download_url=https://nodejs.org/dist/v18.20.8/node-v18.20.8-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v18.20.8/node-v18.20.8-linux-x64.tar.xz"
    source-checksum = "sha256:5467ee62d6af1411d46b6a10e3fb5cacc92734dbcef465fea14e7b90993001c9"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v18.20.8/node-v18.20.8-linux-x64.tar.xz"
    version = "18.20.8"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:224e569dbe7b0ea4628ce383d9d482494b57ee040566583f1c54072c86d1116b"
    cpe = "cpe:2.3:a:nodejs:node.js:18.20.8:*:*:*:*:*:*:*"
    deprecation_date = "2025-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "Zlib", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v18.20.8?checksum=224e569dbe7b0ea4628ce383d9d482494b57ee040566583f1c54072c86d1116b&download_url=https://nodejs.org/dist/v18.20.8/node-v18.20.8-linux-arm64.tar.xz"
    source = "https://nodejs.org/dist/v18.20.8/node-v18.20.8-linux-arm64.tar.xz"
    source-checksum = "sha256:224e569dbe7b0ea4628ce383d9d482494b57ee040566583f1c54072c86d1116b"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v18.20.8/node-v18.20.8-linux-arm64.tar.xz"
    version = "18.20.8"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:315046739a513a70e03a4a55a8afda8cf979f30852e576075c340084e3f8ac0f"
    cpe = "cpe:2.3:a:nodejs:node.js:20.19.5:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "Zlib", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v20.19.5?checksum=315046739a513a70e03a4a55a8afda8cf979f30852e576075c340084e3f8ac0f&download_url=https://nodejs.org/dist/v20.19.5/node-v20.19.5-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v20.19.5/node-v20.19.5-linux-x64.tar.xz"
    source-checksum = "sha256:315046739a513a70e03a4a55a8afda8cf979f30852e576075c340084e3f8ac0f"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v20.19.5/node-v20.19.5-linux-x64.tar.xz"
    version = "20.19.5"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:d462267863ae8ee556039ebdf559055a8ec562c633889ef1403f3adb449ba1dd"
    cpe = "cpe:2.3:a:nodejs:node.js:20.19.5:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "Zlib", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v20.19.5?checksum=d462267863ae8ee556039ebdf559055a8ec562c633889ef1403f3adb449ba1dd&download_url=https://nodejs.org/dist/v20.19.5/node-v20.19.5-linux-arm64.tar.xz"
    source = "https://nodejs.org/dist/v20.19.5/node-v20.19.5-linux-arm64.tar.xz"
    source-checksum = "sha256:d462267863ae8ee556039ebdf559055a8ec562c633889ef1403f3adb449ba1dd"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v20.19.5/node-v20.19.5-linux-arm64.tar.xz"
    version = "20.19.5"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:c514127107ebf6e3885f793b06674574d71fe22e3df91a78c52c5a6f84b3b5b0"
    cpe = "cpe:2.3:a:nodejs:node.js:20.19.6:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "Zlib", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v20.19.6?checksum=c514127107ebf6e3885f793b06674574d71fe22e3df91a78c52c5a6f84b3b5b0&download_url=https://nodejs.org/dist/v20.19.6/node-v20.19.6-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v20.19.6/node-v20.19.6-linux-x64.tar.xz"
    source-checksum = "sha256:c514127107ebf6e3885f793b06674574d71fe22e3df91a78c52c5a6f84b3b5b0"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v20.19.6/node-v20.19.6-linux-x64.tar.xz"
    version = "20.19.6"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:e24741779ae4c2f3c79b362fa5c0c8bbcdca1a6240eb5906c58dc762dcb62e0e"
    cpe = "cpe:2.3:a:nodejs:node.js:20.19.6:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "Zlib", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v20.19.6?checksum=e24741779ae4c2f3c79b362fa5c0c8bbcdca1a6240eb5906c58dc762dcb62e0e&download_url=https://nodejs.org/dist/v20.19.6/node-v20.19.6-linux-arm64.tar.xz"
    source = "https://nodejs.org/dist/v20.19.6/node-v20.19.6-linux-arm64.tar.xz"
    source-checksum = "sha256:e24741779ae4c2f3c79b362fa5c0c8bbcdca1a6240eb5906c58dc762dcb62e0e"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v20.19.6/node-v20.19.6-linux-arm64.tar.xz"
    version = "20.19.6"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:71a04f4b9144870c9407b8019fe912514229e50246bc706862eded3ac8e9025d"
    cpe = "cpe:2.3:a:nodejs:node.js:22.21.0:*:*:*:*:*:*:*"
    deprecation_date = "2027-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v22.21.0?checksum=71a04f4b9144870c9407b8019fe912514229e50246bc706862eded3ac8e9025d&download_url=https://nodejs.org/dist/v22.21.0/node-v22.21.0-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v22.21.0/node-v22.21.0-linux-x64.tar.xz"
    source-checksum = "sha256:71a04f4b9144870c9407b8019fe912514229e50246bc706862eded3ac8e9025d"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v22.21.0/node-v22.21.0-linux-x64.tar.xz"
    version = "22.21.0"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:fe3e371f6f72d07a3f75a94a54c97d652ace6bfcc48f82cc0867f0c0722b84bd"
    cpe = "cpe:2.3:a:nodejs:node.js:22.21.0:*:*:*:*:*:*:*"
    deprecation_date = "2027-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v22.21.0?checksum=fe3e371f6f72d07a3f75a94a54c97d652ace6bfcc48f82cc0867f0c0722b84bd&download_url=https://nodejs.org/dist/v22.21.0/node-v22.21.0-linux-arm64.tar.xz"
    source = "https://nodejs.org/dist/v22.21.0/node-v22.21.0-linux-arm64.tar.xz"
    source-checksum = "sha256:fe3e371f6f72d07a3f75a94a54c97d652ace6bfcc48f82cc0867f0c0722b84bd"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v22.21.0/node-v22.21.0-linux-arm64.tar.xz"
    version = "22.21.0"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:680d3f30b24a7ff24b98db5e96f294c0070f8f9078df658da1bce1b9c9873c88"
    cpe = "cpe:2.3:a:nodejs:node.js:22.21.1:*:*:*:*:*:*:*"
    deprecation_date = "2027-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v22.21.1?checksum=680d3f30b24a7ff24b98db5e96f294c0070f8f9078df658da1bce1b9c9873c88&download_url=https://nodejs.org/dist/v22.21.1/node-v22.21.1-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v22.21.1/node-v22.21.1-linux-x64.tar.xz"
    source-checksum = "sha256:680d3f30b24a7ff24b98db5e96f294c0070f8f9078df658da1bce1b9c9873c88"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v22.21.1/node-v22.21.1-linux-x64.tar.xz"
    version = "22.21.1"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:e660365729b434af422bcd2e8e14228637ecf24a1de2cd7c916ad48f2a0521e1"
    cpe = "cpe:2.3:a:nodejs:node.js:22.21.1:*:*:*:*:*:*:*"
    deprecation_date = "2027-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v22.21.1?checksum=e660365729b434af422bcd2e8e14228637ecf24a1de2cd7c916ad48f2a0521e1&download_url=https://nodejs.org/dist/v22.21.1/node-v22.21.1-linux-arm64.tar.xz"
    source = "https://nodejs.org/dist/v22.21.1/node-v22.21.1-linux-arm64.tar.xz"
    source-checksum = "sha256:e660365729b434af422bcd2e8e14228637ecf24a1de2cd7c916ad48f2a0521e1"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v22.21.1/node-v22.21.1-linux-arm64.tar.xz"
    version = "22.21.1"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:46da9a098973ab7ba4fca76945581ecb2eaf468de347173897044382f10e0a0a"
    cpe = "cpe:2.3:a:nodejs:node.js:24.11.0:*:*:*:*:*:*:*"
    deprecation_date = "2028-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v24.11.0?checksum=46da9a098973ab7ba4fca76945581ecb2eaf468de347173897044382f10e0a0a&download_url=https://nodejs.org/dist/v24.11.0/node-v24.11.0-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v24.11.0/node-v24.11.0-linux-x64.tar.xz"
    source-checksum = "sha256:46da9a098973ab7ba4fca76945581ecb2eaf468de347173897044382f10e0a0a"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v24.11.0/node-v24.11.0-linux-x64.tar.xz"
    version = "24.11.0"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:33a6673b2c7bffeae9deec7f9f8b31aad9119b08f13d49b2ca3ee3bebfe8260f"
    cpe = "cpe:2.3:a:nodejs:node.js:24.11.0:*:*:*:*:*:*:*"
    deprecation_date = "2028-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v24.11.0?checksum=33a6673b2c7bffeae9deec7f9f8b31aad9119b08f13d49b2ca3ee3bebfe8260f&download_url=https://nodejs.org/dist/v24.11.0/node-v24.11.0-linux-arm64.tar.xz"
    source = "https://nodejs.org/dist/v24.11.0/node-v24.11.0-linux-arm64.tar.xz"
    source-checksum = "sha256:33a6673b2c7bffeae9deec7f9f8b31aad9119b08f13d49b2ca3ee3bebfe8260f"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v24.11.0/node-v24.11.0-linux-arm64.tar.xz"
    version = "24.11.0"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:60e3b0a8500819514aca603487c254298cd776de0698d3cd08f11dba5b8289a8"
    cpe = "cpe:2.3:a:nodejs:node.js:24.11.1:*:*:*:*:*:*:*"
    deprecation_date = "2028-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v24.11.1?checksum=60e3b0a8500819514aca603487c254298cd776de0698d3cd08f11dba5b8289a8&download_url=https://nodejs.org/dist/v24.11.1/node-v24.11.1-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v24.11.1/node-v24.11.1-linux-x64.tar.xz"
    source-checksum = "sha256:60e3b0a8500819514aca603487c254298cd776de0698d3cd08f11dba5b8289a8"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v24.11.1/node-v24.11.1-linux-x64.tar.xz"
    version = "24.11.1"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:6b0863fb9f627bf4a6c5948dce1de4398174a2e05dbe717503d828e211ca01f0"
    cpe = "cpe:2.3:a:nodejs:node.js:24.11.1:*:*:*:*:*:*:*"
    deprecation_date = "2028-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v24.11.1?checksum=6b0863fb9f627bf4a6c5948dce1de4398174a2e05dbe717503d828e211ca01f0&download_url=https://nodejs.org/dist/v24.11.1/node-v24.11.1-linux-arm64.tar.xz"
    source = "https://nodejs.org/dist/v24.11.1/node-v24.11.1-linux-arm64.tar.xz"
    source-checksum = "sha256:6b0863fb9f627bf4a6c5948dce1de4398174a2e05dbe717503d828e211ca01f0"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v24.11.1/node-v24.11.1-linux-arm64.tar.xz"
    version = "24.11.1"

  [[metadata.dependency-constraints]]
    constraint = "18.*"
    id = "node"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "20.*"
    id = "node"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "22.*"
    id = "node"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "24.*"
    id = "node"
    patches = 2

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
