api = "0.7"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/node-engine"
  id = "paketo-buildpacks/node-engine"
  name = "Paketo Node Engine Buildpack"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    node = "16.*.*"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:12.22.9:*:*:*:*:*:*:*"
    deprecation_date = "2022-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "CC0-1.0", "MIT", "MIT-0", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v12.22.9?checksum=592ecc53ed8a64dd1a2eb574b4c85d30656e4aee3a02ef997fa8ad92bf025d6a&download_url=https://nodejs.org/dist/v12.22.9/node-v12.22.9.tar.gz"
    sha256 = "4436ce55d58a147492be6c533ba38b06a36f66e16785e6ce1651bc8e42612883"
    source = "https://nodejs.org/dist/v12.22.9/node-v12.22.9.tar.gz"
    source_sha256 = "592ecc53ed8a64dd1a2eb574b4c85d30656e4aee3a02ef997fa8ad92bf025d6a"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v12.22.9_linux_x64_bionic_4436ce55.tgz"
    version = "12.22.9"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:12.22.10:*:*:*:*:*:*:*"
    deprecation_date = "2022-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "CC0-1.0", "MIT", "MIT-0", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v12.22.10?checksum=1eeec68b530da4aced730e2af9e07a1ced8148337708f37fc8b4eddc3b6dc9e9&download_url=https://nodejs.org/dist/v12.22.10/node-v12.22.10.tar.gz"
    sha256 = "7798495f4ba088490e99969f4034481ee87484e13b992c376998e0f1ccb0fc06"
    source = "https://nodejs.org/dist/v12.22.10/node-v12.22.10.tar.gz"
    source_sha256 = "1eeec68b530da4aced730e2af9e07a1ced8148337708f37fc8b4eddc3b6dc9e9"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v12.22.10_linux_x64_bionic_7798495f.tgz"
    version = "12.22.10"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:14.18.3:*:*:*:*:*:*:*"
    deprecation_date = "2023-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "CC0-1.0", "MIT", "MIT-0", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v14.18.3?checksum=96d51324e4eb9dd88082a1effe328d272a6568121930e51ec089db1b966f891a&download_url=https://nodejs.org/dist/v14.18.3/node-v14.18.3.tar.gz"
    sha256 = "41c58fc22824f0ba91fe257a83f7459877bf5de202dd281f66d3cc4d0c592878"
    source = "https://nodejs.org/dist/v14.18.3/node-v14.18.3.tar.gz"
    source_sha256 = "96d51324e4eb9dd88082a1effe328d272a6568121930e51ec089db1b966f891a"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v14.18.3_linux_x64_bionic_41c58fc2.tgz"
    version = "14.18.3"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:14.19.0:*:*:*:*:*:*:*"
    deprecation_date = "2023-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "CC0-1.0", "MIT", "MIT-0", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v14.19.0?checksum=284cf4824d0c3e79177899519f90c160491c0c642bbf459b72a97679cad8fe87&download_url=https://nodejs.org/dist/v14.19.0/node-v14.19.0.tar.gz"
    sha256 = "ec10180c9689764168ea78d684d840009f18d9f8cd69db2457c109de50ec6203"
    source = "https://nodejs.org/dist/v14.19.0/node-v14.19.0.tar.gz"
    source_sha256 = "284cf4824d0c3e79177899519f90c160491c0c642bbf459b72a97679cad8fe87"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v14.19.0_linux_x64_bionic_ec10180c.tgz"
    version = "14.19.0"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:16.13.2:*:*:*:*:*:*:*"
    deprecation_date = "2024-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "CC0-1.0", "MIT", "MIT-0", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v16.13.2?checksum=cd5a07cae25985704a5b1878355b2793d62d70fc97b8a181ad2bf86201121b08&download_url=https://nodejs.org/dist/v16.13.2/node-v16.13.2.tar.gz"
    sha256 = "c91627e60544d45bbbb9202cd60fb96293da4aa2e469e6fdddcdda37fe3f77c4"
    source = "https://nodejs.org/dist/v16.13.2/node-v16.13.2.tar.gz"
    source_sha256 = "cd5a07cae25985704a5b1878355b2793d62d70fc97b8a181ad2bf86201121b08"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v16.13.2_linux_x64_bionic_c91627e6.tgz"
    version = "16.13.2"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:16.14.0:*:*:*:*:*:*:*"
    deprecation_date = "2024-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "CC0-1.0", "MIT", "MIT-0", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v16.14.0?checksum=29dfce13650f063ff009d18349636333fa4305468b6a8965d442c2e88b1dd60f&download_url=https://nodejs.org/dist/v16.14.0/node-v16.14.0.tar.gz"
    sha256 = "5c9c8f5e980d904f47d3f14afcae025f0d9de2dfa86be94dd65879e08641db4c"
    source = "https://nodejs.org/dist/v16.14.0/node-v16.14.0.tar.gz"
    source_sha256 = "29dfce13650f063ff009d18349636333fa4305468b6a8965d442c2e88b1dd60f"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v16.14.0_linux_x64_bionic_5c9c8f5e.tgz"
    version = "16.14.0"

  [[metadata.dependency-constraints]]
    constraint = "12.*"
    id = "node"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "14.*"
    id = "node"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "16.*"
    id = "node"
    patches = 2

  [[metadata.dependency_deprecation_dates]]
    date = "2022-04-01T00:00:00Z"
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "12.x.x"

  [[metadata.dependency_deprecation_dates]]
    date = "2023-04-30T00:00:00Z"
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "14.x.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
