
[buildpack]
id = "org.cloudfoundry.buildpacks.nodejs"
name = "Node.js Buildpack"
version = "0.0.4"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "aa8ef47382853d7124110203c3773515cff00737f1cd7bce98bd388603141c6d"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v6.15.1/node-v6.15.1-linux-x64.tar.gz"
version = "6.15.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "16abb1a8bcef1bc6339a738b51f5f2a5e7d48f820da2cec3f4912504517f7490"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-6.15.1-linux-x64-cflinuxfs2-16abb1a8.tgz"
version = "6.15.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "c8da2b6c146c4bf3c72b35a879be1a5e6764229702ddf3b0ca159ed74debd381"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-6.15.1-linux-x64-cflinuxfs3-c8da2b6c.tgz"
version = "6.15.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "7f26cd9a2845df23773755a428d61b74fd80d48a991e964d12e85ae90ced81a0"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v6.16.0/node-v6.16.0-linux-x64.tar.gz"
version = "6.16.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "fa3b72020ee4005fd0168bef41a765bbc382e4c4fdf65011f6b1c0b5b631c1ab"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-6.16.0-linux-x64-cflinuxfs2-fa3b7202.tgz"
version = "6.16.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "45f43c544683bf31921a0e47e7c6edccb6115c59171d723a345e585382d962d1"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-6.16.0-linux-x64-cflinuxfs3-45f43c54.tgz"
version = "6.16.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "ae9b04e0ad806dc31242ca02b84a84ea67c978e41f60d94ffca010ed3fe32735"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v8.14.1/node-v8.14.1-linux-x64.tar.gz"
version = "8.14.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "ae41693a9d26a1fa3f55fd4613292d4ada8d55da7f000b5cb94793d04b8dcc08"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.14.1-linux-x64-cflinuxfs2-ae41693a.tgz"
version = "8.14.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "a4e189cbe5b8d8329ca8004b23f510e1b796bc22dbeea00d89f01fcd0612685c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.14.1-linux-x64-cflinuxfs3-a4e189cb.tgz"
version = "8.14.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "dc004e5c0f39c6534232a73100c194bc1446f25e3a6a39b29e2000bb3d139d52"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v8.15.0/node-v8.15.0-linux-x64.tar.gz"
version = "8.15.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "1e19815bf98e0555a9f6cbdb6b3031611718a38cacf7704ffb904be5a7bb9e58"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.15.0-linux-x64-cflinuxfs2-1e19815b.tgz"
version = "8.15.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "974131821556a7272c9025766ab6620e059068c5eb5418eb72abc6c397bac12d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.15.0-linux-x64-cflinuxfs3-97413182.tgz"
version = "8.15.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "c15307591aad4b65e984a3c25f39f5d102524190c1859a3fb7de166ac5e2641c"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v9.11.1/node-v9.11.1-linux-x86.tar.gz"
version = "9.11.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "a008671311b82aac5d30a0c1f40b55f80b79406da9f0f11fd1df5b4d7cfd882b"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-9.11.1-linux-x64-cflinuxfs2-a0086713.tgz"
version = "9.11.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "a7afe5aea16738c92b443b0aced859de422447dfb6da8d23d8c95e78e238f3d6"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-9.11.1-linux-x64-cflinuxfs3-a7afe5ae.tgz"
version = "9.11.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "166cc28bd9c8217c533b2921edd5e980b14f1d670d828e9d40c1d5b37f51496d"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v9.11.2/node-v9.11.2-linux-x64.tar.gz"
version = "9.11.2"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "58d0bbd00dce33927281735870b490175f1135e7ac927cb2ac30edf744476474"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-9.11.2-linux-x64-cflinuxfs2-58d0bbd0.tgz"
version = "9.11.2"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "86e844f98106131e3e2e05c54baa900ecc21294b73b78e2fc79ca39fe93b7b34"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-9.11.2-linux-x64-cflinuxfs3-86e844f9.tgz"
version = "9.11.2"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "331f06e2a5fdeeb0f681adce81bc07682bac0418c114f775d07cdabaa0808726"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.14.2-linux-x64-cflinuxfs2-331f06e2.tgz"
version = "10.14.2"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "f0b4ff9a74cbc0106bbf3ee7715f970101ac5b1bbe814404d7a0673d1da9f674"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v10.15.0/node-v10.15.0-linux-x64.tar.gz"
version = "10.15.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "d1a7fed0e8d379dbd588f67cba937ab87021360e43d8960466f73ece91f6ea41"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.15.0-linux-x64-cflinuxfs2-d1a7fed0.tgz"
version = "10.15.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "b811b474c46e37e3d903a4dd9815dc4f02c26e3aa3ae7d2c08e0b4ca299909a8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.15.0-linux-x64-cflinuxfs3-b811b474.tgz"
version = "10.15.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "ca1dfa9790876409c8d9ecab7b4cdb93e3276cedfc64d56ef1a4ff1778a40214"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v10.15.1/node-v10.15.1-linux-x64.tar.gz"
version = "10.15.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "c18cef62f2fdd97533595e48749f4a2d1b31b9b724b1907a0c69737906b1d177"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.15.1-linux-x64-cflinuxfs3-c18cef62.tgz"
version = "10.15.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "0e872c288724e7de72eaa89d1fbc29979a60cdc8c4c0bc1ea65339328bbaaf4c"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v11.9.0/node-v11.9.0-linux-x64.tar.gz"
version = "11.9.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "6214eecbe1a333179a017d9a19b537b514deb5e21175a8f41caf117e70bf897f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-11.9.0-linux-x64-cflinuxfs3-6214eecb.tgz"
version = "11.9.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "4117de50800ecc6d5f7a9c3989d5497fa9dd37df87a904ac4d49948ab10d39ba"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v11.10.0/node-v11.10.0-linux-x64.tar.gz"
version = "11.10.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "abc80398911b4565af97fbba395a306993af7ae7c3d8d1ba77bf19a712917cc0"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-11.10.0-linux-x64-cflinuxfs3-abc80398.tgz"
version = "11.10.0"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs2"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
