
[buildpack]
id = "org.cloudfoundry.buildpacks.nodejs"
name = "Node.js Buildpack"
version = "0.0.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "da6999ee6e7a6c17e36684bf0447faca61e115669abe98b71c2610f7c49b6601"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v6.14.3/node-v6.14.3-linux-x86.tar.gz"
version = "6.14.3"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "26921908430c3749c93bdc4bc21ba0ff6dbfda4dc36d6a3c5f086fab7f10c378"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-6.14.3-linux-x64-cflinuxfs3-26921908.tgz"
version = "6.14.3"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "d394ea61a51ba3c070838f8696a38f9e47be55af6978e7a074addb742ba0cddc"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v6.14.4/node-v6.14.4-linux-x86.tar.gz"
version = "6.14.4"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "b1f0f41f51c1153defc8d15fd260782d5df3108882591887953747dce8183819"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-6.14.4-linux-x64-cflinuxfs3-b1f0f41f.tgz"
version = "6.14.4"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "e9e6efc1fdcaa7283dc6e2428f8dc88260060ee46fb9e4683a09715c7e3354bf"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v8.11.4/node-v8.11.4-linux-x86.tar.gz"
version = "8.11.4"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "c645a4da0d1276995da83e41f4e9781d1eb08cd3e3b828dac318a9072749bebd"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.11.4-linux-x64-cflinuxfs3-c645a4da.tgz"
version = "8.11.4"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "56ecffbd8a656991f71e4b53ab00af333c97453062cadc20a2103b933088d24d"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v8.12.0/node-v8.12.0-linux-x86.tar.gz"
version = "8.12.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "afec056d008f384cb78c2a1618462bd7be10695ac16faa6dd2f0517d7365ccdf"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.12.0-linux-x64-cflinuxfs3-afec056d.tgz"
version = "8.12.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "c15307591aad4b65e984a3c25f39f5d102524190c1859a3fb7de166ac5e2641c"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v9.11.1/node-v9.11.1-linux-x86.tar.gz"
version = "9.11.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "a7afe5aea16738c92b443b0aced859de422447dfb6da8d23d8c95e78e238f3d6"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-9.11.1-linux-x64-cflinuxfs3-a7afe5ae.tgz"
version = "9.11.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "166cc28bd9c8217c533b2921edd5e980b14f1d670d828e9d40c1d5b37f51496d"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v9.11.2/node-v9.11.2-linux-x64.tar.gz"
version = "9.11.2"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "86e844f98106131e3e2e05c54baa900ecc21294b73b78e2fc79ca39fe93b7b34"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-9.11.2-linux-x64-cflinuxfs3-86e844f9.tgz"
version = "9.11.2"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "8d13d57aaf95177e97d29c0944d79a17de8c3a31ba3fe88d1846cfd907e52111"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v10.12.0/node-v10.12.0-linux-x64.tar.gz"
version = "10.12.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "b702b09eb7198cec42cc2268088ceff3f52961cd52050fc9a312a0ec941a4363"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.12.0-linux-x64-cflinuxfs3-b702b09e.tgz"
version = "10.12.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "b4b5d8f73148dcf277df413bb16827be476f4fa117cbbec2aaabc8cc0a8588e1"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v10.13.0/node-v10.13.0-linux-x64.tar.gz"
version = "10.13.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "941d707aaa07d6bdfc93710fd86296f0f4a720ad0b45a38410e00bd2344c8edc"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.13.0-linux-x64-cflinuxfs3-941d707a.tgz"
version = "10.13.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "e571de4e9b42fc411314d51ff730de37e3cef4d1d31cf4b84854e7a34a454cc7"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v11.0.0/node-v11.0.0-linux-x64.tar.gz"
version = "11.0.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "659c455747e89b6e99c83c529a8700f114e85c93a95fc2243a1afdb5bf124222"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-11.0.0-linux-x64-cflinuxfs3-659c4557.tgz"
version = "11.0.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "52289a646a27511f5808290357798c7ebd4b5132a8fc3bf7d5bf53183b89c668"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v11.1.0/node-v11.1.0-linux-x64.tar.gz"
version = "11.1.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "50c1dea69f3526a2ca3b470a086fcc1c2fda1287269b32d4050d8c7a7ec5b192"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-11.1.0-linux-x64-cflinuxfs3-50c1dea6.tgz"
version = "11.1.0"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
