
[buildpack]
id = "org.cloudfoundry.buildpacks.nodejs"
name = "Node.js Buildpack"
version = "0.0.4"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "7f26cd9a2845df23773755a428d61b74fd80d48a991e964d12e85ae90ced81a0"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v6.16.0/node-v6.16.0-linux-x64.tar.gz"
version = "6.16.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "fa3b72020ee4005fd0168bef41a765bbc382e4c4fdf65011f6b1c0b5b631c1ab"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-6.16.0-linux-x64-cflinuxfs2-fa3b7202.tgz"
version = "6.16.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "45f43c544683bf31921a0e47e7c6edccb6115c59171d723a345e585382d962d1"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-6.16.0-linux-x64-cflinuxfs3-45f43c54.tgz"
version = "6.16.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "547422724489a5391d4a137cd130020c73f8f8c721754c67c7692003fe2b6015"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v6.17.0/node-v6.17.0-linux-x64.tar.gz"
version = "6.17.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "d510e3a24c7b617eaf46b166621c6978ebc7fd175e63ef8a970128c9c14edbd8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-6.17.0-linux-x64-cflinuxfs2-d510e3a2.tgz"
version = "6.17.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "7d9e14363e41e8e74610657c7dc08921486680350b8522d2981d50e9a0eb538f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-6.17.0-linux-x64-cflinuxfs3-7d9e1436.tgz"
version = "6.17.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "dc004e5c0f39c6534232a73100c194bc1446f25e3a6a39b29e2000bb3d139d52"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v8.15.0/node-v8.15.0-linux-x64.tar.gz"
version = "8.15.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "1e19815bf98e0555a9f6cbdb6b3031611718a38cacf7704ffb904be5a7bb9e58"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.15.0-linux-x64-cflinuxfs2-1e19815b.tgz"
version = "8.15.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "974131821556a7272c9025766ab6620e059068c5eb5418eb72abc6c397bac12d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.15.0-linux-x64-cflinuxfs3-97413182.tgz"
version = "8.15.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "16e203f2440cffe90522f1e1855d5d7e2e658e759057db070a3dafda445d6d1f"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v8.15.1/node-v8.15.1-linux-x64.tar.gz"
version = "8.15.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "ed20b1fb7feac745e0c5a221caa907f1f66f77c2de2ac9f1e6edb06448f71575"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.15.1-linux-x64-cflinuxfs2-ed20b1fb.tgz"
version = "8.15.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "bed0d0e675f46be256f292e2bf693e59a82ea46eb4d9d593575483d0c4428312"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.15.1-linux-x64-cflinuxfs3-bed0d0e6.tgz"
version = "8.15.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "c15307591aad4b65e984a3c25f39f5d102524190c1859a3fb7de166ac5e2641c"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v9.11.1/node-v9.11.1-linux-x86.tar.gz"
version = "9.11.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "a008671311b82aac5d30a0c1f40b55f80b79406da9f0f11fd1df5b4d7cfd882b"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-9.11.1-linux-x64-cflinuxfs2-a0086713.tgz"
version = "9.11.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "a7afe5aea16738c92b443b0aced859de422447dfb6da8d23d8c95e78e238f3d6"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-9.11.1-linux-x64-cflinuxfs3-a7afe5ae.tgz"
version = "9.11.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "166cc28bd9c8217c533b2921edd5e980b14f1d670d828e9d40c1d5b37f51496d"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v9.11.2/node-v9.11.2-linux-x64.tar.gz"
version = "9.11.2"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "58d0bbd00dce33927281735870b490175f1135e7ac927cb2ac30edf744476474"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-9.11.2-linux-x64-cflinuxfs2-58d0bbd0.tgz"
version = "9.11.2"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "86e844f98106131e3e2e05c54baa900ecc21294b73b78e2fc79ca39fe93b7b34"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-9.11.2-linux-x64-cflinuxfs3-86e844f9.tgz"
version = "9.11.2"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "331f06e2a5fdeeb0f681adce81bc07682bac0418c114f775d07cdabaa0808726"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.14.2-linux-x64-cflinuxfs2-331f06e2.tgz"
version = "10.14.2"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "d1a7fed0e8d379dbd588f67cba937ab87021360e43d8960466f73ece91f6ea41"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.15.0-linux-x64-cflinuxfs2-d1a7fed0.tgz"
version = "10.15.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "65e66599b275e2c41a882610a841a990e0570ed03bfccc378e031c475a3dae52"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v10.15.2/node-v10.15.2-linux-x64.tar.gz"
version = "10.15.2"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "05ea28a3aeb2ebde8ba0a6aa06c040f6ab7a6da03bbf20400680d9a1938f5984"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.15.2-linux-x64-cflinuxfs3-05ea28a3.tgz"
version = "10.15.2"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "6c35b85a7cd4188ab7578354277b2b2ca43eacc864a2a16b3669753ec2369d52"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v10.15.3/node-v10.15.3-linux-x64.tar.gz"
version = "10.15.3"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "52dbc618aa035840763c991688de7aeed0be2eff9d115cddcd09e09055266620"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.15.3-linux-x64-cflinuxfs3-52dbc618.tgz"
version = "10.15.3"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "f749e64a56dc71938fa5d2774b4e53068d19ad9f48b4a62257633b25459bffa6"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v11.11.0/node-v11.11.0-linux-x64.tar.gz"
version = "11.11.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "35764a0a3f3c634bc3328999cd18b552ca6b8d461c2d23092fbc378cc27db1a5"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-11.11.0-linux-x64-cflinuxfs3-35764a0a.tgz"
version = "11.11.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "58be8912097b93098bbbc3c1b536b2f9e70efdca64d63d7e4cdb4dbd40b3e751"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v11.12.0/node-v11.12.0-linux-x64.tar.gz"
version = "11.12.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "79181ca8a0930ffe78f61cf187f97b3ae2c88e8b04ec7567c30d8a797838c310"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-11.12.0-linux-x64-cflinuxfs3-79181ca8.tgz"
version = "11.12.0"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs2"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
