api = "0.7"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/node-engine"
  id = "paketo-buildpacks/node-engine"
  name = "Paketo Buildpack for Node Engine"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/node-engine/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "bin/optimize-memory", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    node = "18.*.*"

  [[metadata.dependencies]]
    checksum = "sha256:e7177fe9c65742047914d5a16745a44dbe70cec53d7057556603257ac26b2aef"
    cpe = "cpe:2.3:a:nodejs:node.js:14.21.2:*:*:*:*:*:*:*"
    deprecation_date = "2023-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "MIT", "MIT-0", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v14.21.2?checksum=aad2b8ac4808a069648caf0dcc938a7a01265c1efcdeb7329a7cc9474f2b87eb&download_url=https://nodejs.org/dist/v14.21.2/node-v14.21.2.tar.gz"
    source = "https://nodejs.org/dist/v14.21.2/node-v14.21.2.tar.gz"
    source-checksum = "sha256:aad2b8ac4808a069648caf0dcc938a7a01265c1efcdeb7329a7cc9474f2b87eb"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/node/node_v14.21.2_linux_x64_bionic_e7177fe9.tgz"
    version = "14.21.2"

  [[metadata.dependencies]]
    checksum = "sha256:c73b52b6f2ae5a07e8c8eb626915557065b7f02b7e7c2faff293a71101461f86"
    cpe = "cpe:2.3:a:nodejs:node.js:14.21.2:*:*:*:*:*:*:*"
    deprecation_date = "2023-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "MIT", "MIT-0", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v14.21.2?checksum=c73b52b6f2ae5a07e8c8eb626915557065b7f02b7e7c2faff293a71101461f86&download_url=https://nodejs.org/dist/v14.21.2/node-v14.21.2-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v14.21.2/node-v14.21.2-linux-x64.tar.xz"
    source-checksum = "sha256:c73b52b6f2ae5a07e8c8eb626915557065b7f02b7e7c2faff293a71101461f86"
    stacks = ["io.buildpacks.stacks.jammy"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v14.21.2/node-v14.21.2-linux-x64.tar.xz"
    version = "14.21.2"

  [[metadata.dependencies]]
    checksum = "sha256:14e509064d0637ab05c023d3c4f34e3b8a4aa30f6476d085ab37c9e47ac6a5cb"
    cpe = "cpe:2.3:a:nodejs:node.js:14.21.3:*:*:*:*:*:*:*"
    deprecation_date = "2023-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "MIT", "MIT-0", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v14.21.3?checksum=05c08a107c50572ab39ce9e8663a2a2d696b5d262d5bd6f98d84b997ce932d9a&download_url=https://nodejs.org/dist/v14.21.3/node-v14.21.3-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v14.21.3/node-v14.21.3-linux-x64.tar.xz"
    source-checksum = "sha256:05c08a107c50572ab39ce9e8663a2a2d696b5d262d5bd6f98d84b997ce932d9a"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/node/node_v14.21.3_linux_x64_bionic_14e50906.tgz"
    version = "14.21.3"

  [[metadata.dependencies]]
    checksum = "sha256:05c08a107c50572ab39ce9e8663a2a2d696b5d262d5bd6f98d84b997ce932d9a"
    cpe = "cpe:2.3:a:nodejs:node.js:14.21.3:*:*:*:*:*:*:*"
    deprecation_date = "2023-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "MIT", "MIT-0", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v14.21.3?checksum=05c08a107c50572ab39ce9e8663a2a2d696b5d262d5bd6f98d84b997ce932d9a&download_url=https://nodejs.org/dist/v14.21.3/node-v14.21.3-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v14.21.3/node-v14.21.3-linux-x64.tar.xz"
    source-checksum = "sha256:05c08a107c50572ab39ce9e8663a2a2d696b5d262d5bd6f98d84b997ce932d9a"
    stacks = ["io.buildpacks.stacks.jammy"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v14.21.3/node-v14.21.3-linux-x64.tar.xz"
    version = "14.21.3"

  [[metadata.dependencies]]
    checksum = "sha256:9d4f5fcafb8e67f5fb251f661d27634bba27899c89b712f84d4fd2bbc89f91ea"
    cpe = "cpe:2.3:a:nodejs:node.js:16.20.1:*:*:*:*:*:*:*"
    deprecation_date = "2023-09-11T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ICU", "MIT", "MIT-0", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v16.20.1?checksum=b6c60e1e106ad7d8881e83945a5208c1b1d1b63e6901c04b9dafa607aff3a154&download_url=https://nodejs.org/dist/v16.20.1/node-v16.20.1-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v16.20.1/node-v16.20.1-linux-x64.tar.xz"
    source-checksum = "sha256:b6c60e1e106ad7d8881e83945a5208c1b1d1b63e6901c04b9dafa607aff3a154"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/node/node_v16.20.1_linux_x64_bionic_9d4f5fca.tgz"
    version = "16.20.1"

  [[metadata.dependencies]]
    checksum = "sha256:b6c60e1e106ad7d8881e83945a5208c1b1d1b63e6901c04b9dafa607aff3a154"
    cpe = "cpe:2.3:a:nodejs:node.js:16.20.1:*:*:*:*:*:*:*"
    deprecation_date = "2023-09-11T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ICU", "MIT", "MIT-0", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v16.20.1?checksum=b6c60e1e106ad7d8881e83945a5208c1b1d1b63e6901c04b9dafa607aff3a154&download_url=https://nodejs.org/dist/v16.20.1/node-v16.20.1-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v16.20.1/node-v16.20.1-linux-x64.tar.xz"
    source-checksum = "sha256:b6c60e1e106ad7d8881e83945a5208c1b1d1b63e6901c04b9dafa607aff3a154"
    stacks = ["io.buildpacks.stacks.jammy"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v16.20.1/node-v16.20.1-linux-x64.tar.xz"
    version = "16.20.1"

  [[metadata.dependencies]]
    checksum = "sha256:d51c5b4049043dfb6eee9ba2beddb1438ff2abe70da056a48ae527e123635cf9"
    cpe = "cpe:2.3:a:nodejs:node.js:16.20.2:*:*:*:*:*:*:*"
    deprecation_date = "2023-09-11T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ICU", "MIT", "MIT-0", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v16.20.2?checksum=874463523f26ed528634580247f403d200ba17a31adf2de98a7b124c6eb33d87&download_url=https://nodejs.org/dist/v16.20.2/node-v16.20.2-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v16.20.2/node-v16.20.2-linux-x64.tar.xz"
    source-checksum = "sha256:874463523f26ed528634580247f403d200ba17a31adf2de98a7b124c6eb33d87"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/node/node_v16.20.2_linux_x64_bionic_d51c5b40.tgz"
    version = "16.20.2"

  [[metadata.dependencies]]
    checksum = "sha256:874463523f26ed528634580247f403d200ba17a31adf2de98a7b124c6eb33d87"
    cpe = "cpe:2.3:a:nodejs:node.js:16.20.2:*:*:*:*:*:*:*"
    deprecation_date = "2023-09-11T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ICU", "MIT", "MIT-0", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v16.20.2?checksum=874463523f26ed528634580247f403d200ba17a31adf2de98a7b124c6eb33d87&download_url=https://nodejs.org/dist/v16.20.2/node-v16.20.2-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v16.20.2/node-v16.20.2-linux-x64.tar.xz"
    source-checksum = "sha256:874463523f26ed528634580247f403d200ba17a31adf2de98a7b124c6eb33d87"
    stacks = ["io.buildpacks.stacks.jammy"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v16.20.2/node-v16.20.2-linux-x64.tar.xz"
    version = "16.20.2"

  [[metadata.dependencies]]
    checksum = "sha256:b131f7ae91a6fe507b1c582f5f2520dc590924cb719e5c2863cea7d47e780395"
    cpe = "cpe:2.3:a:nodejs:node.js:18.17.0:*:*:*:*:*:*:*"
    deprecation_date = "2025-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "MIT", "MIT-0", "SHL-0.5", "SHL-0.51", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v18.17.0?checksum=f36facda28c4d5ce76b3a1b4344e688d29d9254943a47f2f1909b1a10acb1959&download_url=https://nodejs.org/dist/v18.17.0/node-v18.17.0-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v18.17.0/node-v18.17.0-linux-x64.tar.xz"
    source-checksum = "sha256:f36facda28c4d5ce76b3a1b4344e688d29d9254943a47f2f1909b1a10acb1959"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/node/node_v18.17.0_linux_x64_bionic_b131f7ae.tgz"
    version = "18.17.0"

  [[metadata.dependencies]]
    checksum = "sha256:f36facda28c4d5ce76b3a1b4344e688d29d9254943a47f2f1909b1a10acb1959"
    cpe = "cpe:2.3:a:nodejs:node.js:18.17.0:*:*:*:*:*:*:*"
    deprecation_date = "2025-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "MIT", "MIT-0", "SHL-0.5", "SHL-0.51", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v18.17.0?checksum=f36facda28c4d5ce76b3a1b4344e688d29d9254943a47f2f1909b1a10acb1959&download_url=https://nodejs.org/dist/v18.17.0/node-v18.17.0-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v18.17.0/node-v18.17.0-linux-x64.tar.xz"
    source-checksum = "sha256:f36facda28c4d5ce76b3a1b4344e688d29d9254943a47f2f1909b1a10acb1959"
    stacks = ["io.buildpacks.stacks.jammy"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v18.17.0/node-v18.17.0-linux-x64.tar.xz"
    version = "18.17.0"

  [[metadata.dependencies]]
    checksum = "sha256:0b3993009942b5cd8102483767228addb23d17aca9bbb87e56a2d6c4e3867ceb"
    cpe = "cpe:2.3:a:nodejs:node.js:18.17.1:*:*:*:*:*:*:*"
    deprecation_date = "2025-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "MIT", "MIT-0", "SHL-0.5", "SHL-0.51", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v18.17.1?checksum=07e76408ddb0300a6f46fcc9abc61f841acde49b45020ec4e86bb9b25df4dced&download_url=https://nodejs.org/dist/v18.17.1/node-v18.17.1-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v18.17.1/node-v18.17.1-linux-x64.tar.xz"
    source-checksum = "sha256:07e76408ddb0300a6f46fcc9abc61f841acde49b45020ec4e86bb9b25df4dced"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/node/node_v18.17.1_linux_x64_bionic_0b399300.tgz"
    version = "18.17.1"

  [[metadata.dependencies]]
    checksum = "sha256:07e76408ddb0300a6f46fcc9abc61f841acde49b45020ec4e86bb9b25df4dced"
    cpe = "cpe:2.3:a:nodejs:node.js:18.17.1:*:*:*:*:*:*:*"
    deprecation_date = "2025-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "MIT", "MIT-0", "SHL-0.5", "SHL-0.51", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v18.17.1?checksum=07e76408ddb0300a6f46fcc9abc61f841acde49b45020ec4e86bb9b25df4dced&download_url=https://nodejs.org/dist/v18.17.1/node-v18.17.1-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v18.17.1/node-v18.17.1-linux-x64.tar.xz"
    source-checksum = "sha256:07e76408ddb0300a6f46fcc9abc61f841acde49b45020ec4e86bb9b25df4dced"
    stacks = ["io.buildpacks.stacks.jammy"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v18.17.1/node-v18.17.1-linux-x64.tar.xz"
    version = "18.17.1"

  [[metadata.dependencies]]
    checksum = "sha256:a4269bb04894442de0236b7da13719d911832ad46a6f5d51bf891c7ac2c76b5d"
    cpe = "cpe:2.3:a:nodejs:node.js:19.8.1:*:*:*:*:*:*:*"
    deprecation_date = "2023-06-01T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "MIT", "MIT-0", "SHL-0.5", "SHL-0.51", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v19.8.1?checksum=b8ecd95eebda5882bb70c1088595d87a1fd69cc4be81c317191f4f5ebb34b7ac&download_url=https://nodejs.org/dist/v19.8.1/node-v19.8.1-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v19.8.1/node-v19.8.1-linux-x64.tar.xz"
    source-checksum = "sha256:b8ecd95eebda5882bb70c1088595d87a1fd69cc4be81c317191f4f5ebb34b7ac"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/node/node_v19.8.1_linux_x64_bionic_a4269bb0.tgz"
    version = "19.8.1"

  [[metadata.dependencies]]
    checksum = "sha256:b8ecd95eebda5882bb70c1088595d87a1fd69cc4be81c317191f4f5ebb34b7ac"
    cpe = "cpe:2.3:a:nodejs:node.js:19.8.1:*:*:*:*:*:*:*"
    deprecation_date = "2023-06-01T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "MIT", "MIT-0", "SHL-0.5", "SHL-0.51", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v19.8.1?checksum=b8ecd95eebda5882bb70c1088595d87a1fd69cc4be81c317191f4f5ebb34b7ac&download_url=https://nodejs.org/dist/v19.8.1/node-v19.8.1-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v19.8.1/node-v19.8.1-linux-x64.tar.xz"
    source-checksum = "sha256:b8ecd95eebda5882bb70c1088595d87a1fd69cc4be81c317191f4f5ebb34b7ac"
    stacks = ["io.buildpacks.stacks.jammy"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v19.8.1/node-v19.8.1-linux-x64.tar.xz"
    version = "19.8.1"

  [[metadata.dependencies]]
    checksum = "sha256:3f5e24807055f5f5da81f4fa9707e7d164fa7d0ad059253923703c20155bbceb"
    cpe = "cpe:2.3:a:nodejs:node.js:19.9.0:*:*:*:*:*:*:*"
    deprecation_date = "2023-06-01T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "MIT", "MIT-0", "SHL-0.5", "SHL-0.51", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v19.9.0?checksum=e8ea737ee15a62c8752159d12765ed757b5d4b18036b1011d9e4c9e692a4e58d&download_url=https://nodejs.org/dist/v19.9.0/node-v19.9.0-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v19.9.0/node-v19.9.0-linux-x64.tar.xz"
    source-checksum = "sha256:e8ea737ee15a62c8752159d12765ed757b5d4b18036b1011d9e4c9e692a4e58d"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/node/node_v19.9.0_linux_x64_bionic_3f5e2480.tgz"
    version = "19.9.0"

  [[metadata.dependencies]]
    checksum = "sha256:e8ea737ee15a62c8752159d12765ed757b5d4b18036b1011d9e4c9e692a4e58d"
    cpe = "cpe:2.3:a:nodejs:node.js:19.9.0:*:*:*:*:*:*:*"
    deprecation_date = "2023-06-01T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "MIT", "MIT-0", "SHL-0.5", "SHL-0.51", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v19.9.0?checksum=e8ea737ee15a62c8752159d12765ed757b5d4b18036b1011d9e4c9e692a4e58d&download_url=https://nodejs.org/dist/v19.9.0/node-v19.9.0-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v19.9.0/node-v19.9.0-linux-x64.tar.xz"
    source-checksum = "sha256:e8ea737ee15a62c8752159d12765ed757b5d4b18036b1011d9e4c9e692a4e58d"
    stacks = ["io.buildpacks.stacks.jammy"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v19.9.0/node-v19.9.0-linux-x64.tar.xz"
    version = "19.9.0"

  [[metadata.dependency-constraints]]
    constraint = "14.*"
    id = "node"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "16.*"
    id = "node"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "18.*"
    id = "node"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "19.*"
    id = "node"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.buildpacks.stacks.jammy"

[[stacks]]
  id = "*"
