api = "0.4"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/node-engine"
  id = "paketo-buildpacks/node-engine"
  name = "Paketo Node Engine Buildpack"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    node = "14.*.*"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:12.22.2:*:*:*:*:*:*:*"
    deprecation_date = "2022-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "CC0-1.0", "MIT", "MIT-0", "Unicode-TOU"]
    name = "Node Engine"
    sha256 = "72afae595cd1353ad21544d4328d9b5d5651ff6044b29dc1e26ff7436462762c"
    source = "https://nodejs.org/dist/v12.22.2/node-v12.22.2.tar.gz"
    source_sha256 = "210a550c47056f29537e1b5b73cb78a88c44609c3b92aa003cf7862d3904ef99"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v12.22.2_linux_x64_bionic_72afae59.tgz"
    version = "12.22.2"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:12.22.3:*:*:*:*:*:*:*"
    deprecation_date = "2022-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "CC0-1.0", "MIT", "MIT-0", "Unicode-TOU"]
    name = "Node Engine"
    sha256 = "ec5e459a40dc0de9a08837d38b32eb4ab5d6480fd74e9560d5cbc58b5d7131df"
    source = "https://nodejs.org/dist/v12.22.3/node-v12.22.3.tar.gz"
    source_sha256 = "30acec454f26a168afe6d1c55307c5186ef23dba66527cc34e4497d01f91bda4"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v12.22.3_linux_x64_bionic_ec5e459a.tgz"
    version = "12.22.3"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:14.17.2:*:*:*:*:*:*:*"
    deprecation_date = "2023-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "CC0-1.0", "MIT", "MIT-0", "Unicode-TOU"]
    name = "Node Engine"
    sha256 = "83d999aae0a9ce23b2c6dda3a22c3749272968cb7db2ed80d4279643d50df4c6"
    source = "https://nodejs.org/dist/v14.17.2/node-v14.17.2.tar.gz"
    source_sha256 = "03bea54a68c6fa8b520c273a1dc80f2fdbf80ddc9c303200d2eeaf25bd7e62fa"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v14.17.2_linux_x64_bionic_83d999aa.tgz"
    version = "14.17.2"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:14.17.3:*:*:*:*:*:*:*"
    deprecation_date = "2023-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "CC0-1.0", "MIT", "MIT-0", "Unicode-TOU"]
    name = "Node Engine"
    sha256 = "05827c6e629880599edf70ef5e5889f4338bc72c74c22b1a442638cc70bf0d6b"
    source = "https://nodejs.org/dist/v14.17.3/node-v14.17.3.tar.gz"
    source_sha256 = "dcbd156506ee79ee48439257626ca0a6db3d7eab8cb0208db6979125ae7d3a95"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v14.17.3_linux_x64_bionic_05827c6e.tgz"
    version = "14.17.3"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:15.13.0:*:*:*:*:*:*:*"
    deprecation_date = "2021-06-01T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "CC0-1.0", "MIT", "MIT-0", "Unicode-TOU"]
    name = "Node Engine"
    sha256 = "1ddd140fa72ed2b66f666231da512f9e593d4ea99a0b80e011a72056f5eba9ef"
    source = "https://nodejs.org/dist/v15.13.0/node-v15.13.0.tar.gz"
    source_sha256 = "96926e5b8f2f3ea805596448f01b16115882f3a594e2e999dc7349f80b3ec1f8"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v15.13.0_linux_x64_bionic_1ddd140f.tgz"
    version = "15.13.0"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:15.14.0:*:*:*:*:*:*:*"
    deprecation_date = "2021-06-01T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "CC0-1.0", "MIT", "MIT-0", "Unicode-TOU"]
    name = "Node Engine"
    sha256 = "e04f8e8c133af229f737d9059ef25e9b2a490dd0fdabb5367f00ef5c8cadf71e"
    source = "https://nodejs.org/dist/v15.14.0/node-v15.14.0.tar.gz"
    source_sha256 = "f3a35c1b29b58846575085fdee7774d78b75ff4cf1e52572afce7f38685b159a"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v15.14.0_linux_x64_bionic_e04f8e8c.tgz"
    version = "15.14.0"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:16.4.2:*:*:*:*:*:*:*"
    deprecation_date = "2024-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "CC0-1.0", "MIT", "MIT-0", "Unicode-TOU"]
    name = "Node Engine"
    sha256 = "fb5093f665d64b9db84f992b9326bab33a36c8031f6d9ed17dd78f1269500848"
    source = "https://nodejs.org/dist/v16.4.2/node-v16.4.2.tar.gz"
    source_sha256 = "46d907a06fe020ee8d7e6753357b82edd16f3871f8caaa188841d29d265de7bd"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v16.4.2_linux_x64_bionic_fb5093f6.tgz"
    version = "16.4.2"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:16.5.0:*:*:*:*:*:*:*"
    deprecation_date = "2024-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "CC0-1.0", "MIT", "MIT-0", "Unicode-TOU"]
    name = "Node Engine"
    sha256 = "d4f42169dc9dfd97e45dd133fca84ba6389134cd0968e62e60dd1f11e95f6047"
    source = "https://nodejs.org/dist/v16.5.0/node-v16.5.0.tar.gz"
    source_sha256 = "a0d233cde072822af7fd3043b866e526a1739df32c3ace6210ae289f3266ccb7"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v16.5.0_linux_x64_bionic_d4f42169.tgz"
    version = "16.5.0"

  [[metadata.dependency-constraints]]
    constraint = "12.*"
    id = "node"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "14.*"
    id = "node"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "15.*"
    id = "node"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "16.*"
    id = "node"
    patches = 2

  [[metadata.dependency_deprecation_dates]]
    date = "2022-04-01T00:00:00Z"
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "12.x.x"

  [[metadata.dependency_deprecation_dates]]
    date = "2023-04-30T00:00:00Z"
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "14.x.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
