api = "0.10"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/node-engine"
  id = "paketo-buildpacks/node-engine"
  name = "Paketo Buildpack for Node Engine"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/node-engine/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/amd64/bin/optimize-memory", "linux/amd64/bin/inspector", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run", "linux/arm64/bin/optimize-memory", "linux/arm64/bin/inspector", "buildpack.toml"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"
  [metadata.default-versions]
    node = "24.*.*"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:deaf9695966087815a09c1c8e7fb0cfeb5b5b4471836e5993431230a845becad"
    cpe = "cpe:2.3:a:nodejs:node.js:18.20.7:*:*:*:*:*:*:*"
    deprecation_date = "2025-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "Zlib", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v18.20.7?checksum=deaf9695966087815a09c1c8e7fb0cfeb5b5b4471836e5993431230a845becad&download_url=https://nodejs.org/dist/v18.20.7/node-v18.20.7-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v18.20.7/node-v18.20.7-linux-x64.tar.xz"
    source-checksum = "sha256:deaf9695966087815a09c1c8e7fb0cfeb5b5b4471836e5993431230a845becad"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v18.20.7/node-v18.20.7-linux-x64.tar.xz"
    version = "18.20.7"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:c788ad58ded0426a7fca9f3a7e005f57c14a348ebdb3a2977e19ef7b0c143439"
    cpe = "cpe:2.3:a:nodejs:node.js:18.20.7:*:*:*:*:*:*:*"
    deprecation_date = "2025-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "Zlib", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v18.20.7?checksum=c788ad58ded0426a7fca9f3a7e005f57c14a348ebdb3a2977e19ef7b0c143439&download_url=https://nodejs.org/dist/v18.20.7/node-v18.20.7-linux-arm64.tar.xz"
    source = "https://nodejs.org/dist/v18.20.7/node-v18.20.7-linux-arm64.tar.xz"
    source-checksum = "sha256:c788ad58ded0426a7fca9f3a7e005f57c14a348ebdb3a2977e19ef7b0c143439"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v18.20.7/node-v18.20.7-linux-arm64.tar.xz"
    version = "18.20.7"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:5467ee62d6af1411d46b6a10e3fb5cacc92734dbcef465fea14e7b90993001c9"
    cpe = "cpe:2.3:a:nodejs:node.js:18.20.8:*:*:*:*:*:*:*"
    deprecation_date = "2025-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "Zlib", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v18.20.8?checksum=5467ee62d6af1411d46b6a10e3fb5cacc92734dbcef465fea14e7b90993001c9&download_url=https://nodejs.org/dist/v18.20.8/node-v18.20.8-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v18.20.8/node-v18.20.8-linux-x64.tar.xz"
    source-checksum = "sha256:5467ee62d6af1411d46b6a10e3fb5cacc92734dbcef465fea14e7b90993001c9"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v18.20.8/node-v18.20.8-linux-x64.tar.xz"
    version = "18.20.8"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:224e569dbe7b0ea4628ce383d9d482494b57ee040566583f1c54072c86d1116b"
    cpe = "cpe:2.3:a:nodejs:node.js:18.20.8:*:*:*:*:*:*:*"
    deprecation_date = "2025-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "Zlib", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v18.20.8?checksum=224e569dbe7b0ea4628ce383d9d482494b57ee040566583f1c54072c86d1116b&download_url=https://nodejs.org/dist/v18.20.8/node-v18.20.8-linux-arm64.tar.xz"
    source = "https://nodejs.org/dist/v18.20.8/node-v18.20.8-linux-arm64.tar.xz"
    source-checksum = "sha256:224e569dbe7b0ea4628ce383d9d482494b57ee040566583f1c54072c86d1116b"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v18.20.8/node-v18.20.8-linux-arm64.tar.xz"
    version = "18.20.8"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:c514127107ebf6e3885f793b06674574d71fe22e3df91a78c52c5a6f84b3b5b0"
    cpe = "cpe:2.3:a:nodejs:node.js:20.19.6:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "Zlib", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v20.19.6?checksum=c514127107ebf6e3885f793b06674574d71fe22e3df91a78c52c5a6f84b3b5b0&download_url=https://nodejs.org/dist/v20.19.6/node-v20.19.6-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v20.19.6/node-v20.19.6-linux-x64.tar.xz"
    source-checksum = "sha256:c514127107ebf6e3885f793b06674574d71fe22e3df91a78c52c5a6f84b3b5b0"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v20.19.6/node-v20.19.6-linux-x64.tar.xz"
    version = "20.19.6"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:e24741779ae4c2f3c79b362fa5c0c8bbcdca1a6240eb5906c58dc762dcb62e0e"
    cpe = "cpe:2.3:a:nodejs:node.js:20.19.6:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "Zlib", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v20.19.6?checksum=e24741779ae4c2f3c79b362fa5c0c8bbcdca1a6240eb5906c58dc762dcb62e0e&download_url=https://nodejs.org/dist/v20.19.6/node-v20.19.6-linux-arm64.tar.xz"
    source = "https://nodejs.org/dist/v20.19.6/node-v20.19.6-linux-arm64.tar.xz"
    source-checksum = "sha256:e24741779ae4c2f3c79b362fa5c0c8bbcdca1a6240eb5906c58dc762dcb62e0e"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v20.19.6/node-v20.19.6-linux-arm64.tar.xz"
    version = "20.19.6"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:4f48b52acf42130844a3a75e94da0e9629009d09e4101b2304895c24f3fbe609"
    cpe = "cpe:2.3:a:nodejs:node.js:20.20.0:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "Zlib", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v20.20.0?checksum=4f48b52acf42130844a3a75e94da0e9629009d09e4101b2304895c24f3fbe609&download_url=https://nodejs.org/dist/v20.20.0/node-v20.20.0-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v20.20.0/node-v20.20.0-linux-x64.tar.xz"
    source-checksum = "sha256:4f48b52acf42130844a3a75e94da0e9629009d09e4101b2304895c24f3fbe609"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v20.20.0/node-v20.20.0-linux-x64.tar.xz"
    version = "20.20.0"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:752113754a7dddf0622b3740a2b2bec3dbaf1792a18711b55871d76444d8892a"
    cpe = "cpe:2.3:a:nodejs:node.js:20.20.0:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "Zlib", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v20.20.0?checksum=752113754a7dddf0622b3740a2b2bec3dbaf1792a18711b55871d76444d8892a&download_url=https://nodejs.org/dist/v20.20.0/node-v20.20.0-linux-arm64.tar.xz"
    source = "https://nodejs.org/dist/v20.20.0/node-v20.20.0-linux-arm64.tar.xz"
    source-checksum = "sha256:752113754a7dddf0622b3740a2b2bec3dbaf1792a18711b55871d76444d8892a"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v20.20.0/node-v20.20.0-linux-arm64.tar.xz"
    version = "20.20.0"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:680d3f30b24a7ff24b98db5e96f294c0070f8f9078df658da1bce1b9c9873c88"
    cpe = "cpe:2.3:a:nodejs:node.js:22.21.1:*:*:*:*:*:*:*"
    deprecation_date = "2027-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v22.21.1?checksum=680d3f30b24a7ff24b98db5e96f294c0070f8f9078df658da1bce1b9c9873c88&download_url=https://nodejs.org/dist/v22.21.1/node-v22.21.1-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v22.21.1/node-v22.21.1-linux-x64.tar.xz"
    source-checksum = "sha256:680d3f30b24a7ff24b98db5e96f294c0070f8f9078df658da1bce1b9c9873c88"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v22.21.1/node-v22.21.1-linux-x64.tar.xz"
    version = "22.21.1"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:e660365729b434af422bcd2e8e14228637ecf24a1de2cd7c916ad48f2a0521e1"
    cpe = "cpe:2.3:a:nodejs:node.js:22.21.1:*:*:*:*:*:*:*"
    deprecation_date = "2027-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v22.21.1?checksum=e660365729b434af422bcd2e8e14228637ecf24a1de2cd7c916ad48f2a0521e1&download_url=https://nodejs.org/dist/v22.21.1/node-v22.21.1-linux-arm64.tar.xz"
    source = "https://nodejs.org/dist/v22.21.1/node-v22.21.1-linux-arm64.tar.xz"
    source-checksum = "sha256:e660365729b434af422bcd2e8e14228637ecf24a1de2cd7c916ad48f2a0521e1"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v22.21.1/node-v22.21.1-linux-arm64.tar.xz"
    version = "22.21.1"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:9aa8e9d2298ab68c600bd6fb86a6c13bce11a4eca1ba9b39d79fa021755d7c37"
    cpe = "cpe:2.3:a:nodejs:node.js:22.22.0:*:*:*:*:*:*:*"
    deprecation_date = "2027-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v22.22.0?checksum=9aa8e9d2298ab68c600bd6fb86a6c13bce11a4eca1ba9b39d79fa021755d7c37&download_url=https://nodejs.org/dist/v22.22.0/node-v22.22.0-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v22.22.0/node-v22.22.0-linux-x64.tar.xz"
    source-checksum = "sha256:9aa8e9d2298ab68c600bd6fb86a6c13bce11a4eca1ba9b39d79fa021755d7c37"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v22.22.0/node-v22.22.0-linux-x64.tar.xz"
    version = "22.22.0"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:1bf1eb9ee63ffc4e5d324c0b9b62cf4a289f44332dfef9607cea1a0d9596ba6f"
    cpe = "cpe:2.3:a:nodejs:node.js:22.22.0:*:*:*:*:*:*:*"
    deprecation_date = "2027-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v22.22.0?checksum=1bf1eb9ee63ffc4e5d324c0b9b62cf4a289f44332dfef9607cea1a0d9596ba6f&download_url=https://nodejs.org/dist/v22.22.0/node-v22.22.0-linux-arm64.tar.xz"
    source = "https://nodejs.org/dist/v22.22.0/node-v22.22.0-linux-arm64.tar.xz"
    source-checksum = "sha256:1bf1eb9ee63ffc4e5d324c0b9b62cf4a289f44332dfef9607cea1a0d9596ba6f"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v22.22.0/node-v22.22.0-linux-arm64.tar.xz"
    version = "22.22.0"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:bdebee276e58d0ef5448f3d5ac12c67daa963dd5e0a9bb621a53d1cefbc852fd"
    cpe = "cpe:2.3:a:nodejs:node.js:24.12.0:*:*:*:*:*:*:*"
    deprecation_date = "2028-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v24.12.0?checksum=bdebee276e58d0ef5448f3d5ac12c67daa963dd5e0a9bb621a53d1cefbc852fd&download_url=https://nodejs.org/dist/v24.12.0/node-v24.12.0-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v24.12.0/node-v24.12.0-linux-x64.tar.xz"
    source-checksum = "sha256:bdebee276e58d0ef5448f3d5ac12c67daa963dd5e0a9bb621a53d1cefbc852fd"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v24.12.0/node-v24.12.0-linux-x64.tar.xz"
    version = "24.12.0"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:a06d42807fb500f7459e5f3fa6cb431447352826ee6f07e14adfeec58a1b3210"
    cpe = "cpe:2.3:a:nodejs:node.js:24.12.0:*:*:*:*:*:*:*"
    deprecation_date = "2028-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v24.12.0?checksum=a06d42807fb500f7459e5f3fa6cb431447352826ee6f07e14adfeec58a1b3210&download_url=https://nodejs.org/dist/v24.12.0/node-v24.12.0-linux-arm64.tar.xz"
    source = "https://nodejs.org/dist/v24.12.0/node-v24.12.0-linux-arm64.tar.xz"
    source-checksum = "sha256:a06d42807fb500f7459e5f3fa6cb431447352826ee6f07e14adfeec58a1b3210"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v24.12.0/node-v24.12.0-linux-arm64.tar.xz"
    version = "24.12.0"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:e798599612f4bb71333a3397ab0d095fd62214e115aea45aa858a145fc72d67e"
    cpe = "cpe:2.3:a:nodejs:node.js:24.13.0:*:*:*:*:*:*:*"
    deprecation_date = "2028-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v24.13.0?checksum=e798599612f4bb71333a3397ab0d095fd62214e115aea45aa858a145fc72d67e&download_url=https://nodejs.org/dist/v24.13.0/node-v24.13.0-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v24.13.0/node-v24.13.0-linux-x64.tar.xz"
    source-checksum = "sha256:e798599612f4bb71333a3397ab0d095fd62214e115aea45aa858a145fc72d67e"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v24.13.0/node-v24.13.0-linux-x64.tar.xz"
    version = "24.13.0"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:aa881151bd0f9f154a0424dd60a72e9ce10672619121658c278a24327ef46831"
    cpe = "cpe:2.3:a:nodejs:node.js:24.13.0:*:*:*:*:*:*:*"
    deprecation_date = "2028-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "ISC", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Unicode-TOU", "deprecated_BSD-2-Clause-NetBSD"]
    name = "Node Engine"
    os = "linux"
    purl = "pkg:generic/node@v24.13.0?checksum=aa881151bd0f9f154a0424dd60a72e9ce10672619121658c278a24327ef46831&download_url=https://nodejs.org/dist/v24.13.0/node-v24.13.0-linux-arm64.tar.xz"
    source = "https://nodejs.org/dist/v24.13.0/node-v24.13.0-linux-arm64.tar.xz"
    source-checksum = "sha256:aa881151bd0f9f154a0424dd60a72e9ce10672619121658c278a24327ef46831"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v24.13.0/node-v24.13.0-linux-arm64.tar.xz"
    version = "24.13.0"

  [[metadata.dependency-constraints]]
    constraint = "18.*"
    id = "node"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "20.*"
    id = "node"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "22.*"
    id = "node"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "24.*"
    id = "node"
    patches = 2

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
